name: ALICEA CALDAS
favicon: null
layout_spectrum: 0.23436
typography_spectrum: 0.2631
title: ALICEA CALDAS Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#bebebe'
    - '#1b1b1b'
    - '#9a9a9a'
    - '#606060'
  brandStrength: 0.42170450696721673
  lightness: 0.31179759511724114
  saturation: 0.5605719999875873
  rhythmicContrast: 0.25
purpose: []
