name: ALICEA CALDAS
favicon: null
layout_spectrum: 0.23436
typography_spectrum: 0.7521664341911674
title: ALICEA CALDAS Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aa8551'
    - '#ffffff'
    - '#b59a76'
    - '#ede8e1'
    - '#d2bfa4'
  brandStrength: 0.42170450696721673
  lightness: 0.31179759511724114
  saturation: 0.5605719999875873
  rhythmicContrast: 0.021047594724223018
purpose: []
